### ISSUE TITLE
add status code ERR11202 for hybrid-4j get request

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#173]
```
ERR11202:
  statusCode: 400
  code: ERR11202
  message: REQUEST_CMD_EMPTY
  description: Hybrid request cmd parameter is empty for get method.
```
