### ISSUE TITLE
Backwards compatibility for Consul blocking queries time

### ISSUE THREAD

**Issue by jaydeepparekh1311** [networknt/light-4j#1917]
PR: #1932 

The time between Consul blocking queries is configurable.

**In light-4j versions up to 1.6.43**, it is via the registrySessionTimeout parameter in service.yml (this is time in MILLIseconds)

EXAMPLE service.yml snippet:
```
singletons: 
- com.networknt.registry.URL: 
  - com.networknt.registry.URLImpl: 
      protocol: light
      host: localhost
      port: 8500
      path: ''
      parameters: 
        registrySessionTimeout: '30000'
```

**In light-4j 1.6.44**, use of registrySessionTimeout in service.yml was replaced with the use of lookupInterval in consul.yml

EXAMPLE consul.yml snippet:

```
# "SLEEP" time: Time in seconds between blocking queries with Consul
lookupInterval: 30
```

The code change that did this was in ConsulRegistry's constructor:

```
// lookupInterval = getUrl().getIntParameter(URLParamType.registrySessionTimeout.getName(), ConsulConstants.DEFAULT_LOOKUP_INTERVAL);

// added
lookupInterval = getConsulConfig().getLookupInterval() * 1000;
```

Backwards compatibility must be restored. We should go back to using registrySessionTimeout again if lookupInterval is not defined in consul.yml. However, if lookupInterval is defined in consul.yml, it should override registrySessionTimeout.
