### ISSUE TITLE
add an error status code for light-oauth2 client registration

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#229]
```
ERR12043:
  statusCode: 400
  code: ERR12043
  message: DEREF_NOT_EXTERNAL
  description: Only external client type needs optional deref client id

```
