### ISSUE TITLE
add environment tag to the DirectRegistry to support tag based lookup

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#769]
When using consul service discovery, you can pass in a tag parameter to the cluster lookup in order to separate the environments. For some users, they are using DirectRegistry on production although it is not recommended. For these users, we have updated the DirectRegistry to support the environment parameter in the URL configuration in service.yml. 

```
singletons:
- com.networknt.registry.URL:
  - com.networknt.registry.URLImpl:
      protocol: https
      host: localhost
      port: 8080
      path: direct
      parameters:
        com.networknt.apib-1.0.0: http://localhost:7002,http://localhost:7005
        com.networknt.apic-1.0.0: http://localhost:7003
        com.networknt.portal.command-1.0.0: https://localhost:8440?environment=0000,https://localhost:8441?environment=0001,https://localhost:8442?environment=0002
- com.networknt.registry.Registry:
  - com.networknt.registry.support.DirectRegistry
- com.networknt.balance.LoadBalance:
  - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
  - com.networknt.cluster.LightCluster

```
